# Generated by Django 3.1.6 on 2021-02-13 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=128, verbose_name='Asset Type')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=50, verbose_name='Asset Symbol')),
                ('asset_name', models.CharField(max_length=128, verbose_name='Asset Name')),
                ('asset_industry', models.CharField(blank=True, max_length=128, null=True, verbose_name='Asset Industry')),
                ('asset_sector', models.CharField(blank=True, max_length=128, null=True, verbose_name='Asset Sector')),
                ('asset_country', models.CharField(max_length=50, verbose_name='Asset Country')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assettype')),
            ],
        ),
    ]
