# Generated by Django 3.1.6 on 2021-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210213_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
